package eu.uqasar.model.qmtree;

/*
 * #%L
 * U-QASAR
 * %%
 * Copyright (C) 2012 - 2015 U-QASAR Consortium
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;
import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonTypeInfo;
import org.codehaus.jackson.annotate.JsonTypeInfo.As;
import org.codehaus.jackson.annotate.JsonTypeInfo.Id;
import org.hibernate.search.annotations.Indexed;

import de.agilecoders.wicket.core.markup.html.bootstrap.image.IconType;
import eu.uqasar.model.quality.indicator.Domain;
import eu.uqasar.model.quality.indicator.Paradigm;
import eu.uqasar.model.quality.indicator.Purpose;
import eu.uqasar.model.quality.indicator.Version;
import eu.uqasar.model.role.Role;


@Setter
@Getter
@Entity
@XmlRootElement
@Indexed
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {"name","description","domain","indicatorPurpose", "version",
		"paradigm","targetAudience","upperLimit", "lowerLimit", "targetValue", "weight", "children"})
@JsonTypeInfo(use = Id.CLASS, include = As.PROPERTY, property = "@class")
public class QMQualityObjective extends QMBaseIndicator {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8578701944367921751L;

	public static final IconType ICON = new IconType("tasks");
	
	@XmlElementWrapper(name="domains")
	@XmlElement
	@Column
    @ElementCollection(targetClass=Domain.class)
	private List<Domain> domain;
	
	@JsonCreator
	public QMQualityObjective(
			@JsonProperty("name") final String name,
			@JsonProperty("children") final List<QMQualityIndicator> children,
			@JsonProperty("description") final String description,
			@JsonProperty("domain") final List<Domain> domain,
			@JsonProperty("indicatorPurpose") final Purpose indicatorPurpose,
			@JsonProperty("lowerLimit") final float lowerLimit,
			@JsonProperty("paradigm") final Paradigm paradigm,
			@JsonProperty("targetAudience") final List<Role> targetAudience,
			@JsonProperty("targetValue") final float targetValue,
			@JsonProperty("upperLimit") final float upperLimit,
			@JsonProperty("version") final Version version,
			@JsonProperty("weight") final float weight) {
		
		this.setName(name);
		this.setDescription(description);
		this.setDomain(domain);
		this.setIndicatorPurpose(indicatorPurpose);
		this.setLowerLimit((double) lowerLimit);
		this.setParadigm(paradigm);
		this.setTargetAudience(targetAudience);
		this.setTargetValue(targetValue);
		this.setUpperLimit((double) upperLimit);
		this.setVersion(version);
		this.setWeight(weight);
		
		boolean isCompleted = true;
		Iterator<QMQualityIndicator> it = children.iterator();
		List<QMTreeNode> nodes = new LinkedList<>();
		while (it.hasNext()){
			QMQualityIndicator qi = it.next();

			isCompleted = isCompleted && qi.isCompleted();
			nodes.add(qi);
		}
		this.setChildren(nodes);
		this.setCompleted(isCompleted);
	}
	
	
	public QMQualityObjective() {
		this.setCompleted(false);
	}
	
	public QMQualityObjective(final String name, final QModel parent) {
		super(parent);
		this.setName(name);
		this.setCompleted(false);
	}
	
	public QMQualityObjective(final QMQualityObjective copy) {
		super(copy.getQModel());

		this.setDescription(copy.getDescription());
		this.setDomain(copy.getDomain());
		this.setIndicatorPurpose(copy.getIndicatorPurpose());
		this.setCompleted(false);
		//TODO- AUTOGENERATED?  this.setKey("0");
		this.setLifeCycleStage(copy.getLifeCycleStage());
		this.setLowerLimit(copy.getLowerLimit());
		this.setName("Copy of "+copy.getName());
		this.setParadigm(copy.getParadigm());
		this.setRupStage(copy.getRupStage());
		this.setTargetAudience(copy.getTargetAudience());
		this.setTargetValue(copy.getTargetValue());
		this.setUpperLimit(copy.getUpperLimit());
		this.setVersion(copy.getVersion());
		this.setWeight(copy.getWeight());
		this.setQModelTagData(copy.getQModelTagData());
	}
	
	@JsonIgnore
	@Override
	public IconType getIconType() {
		return ICON;
	}
	
	@JsonIgnore
	@Override
	public Class<? extends QMTreeNode> getChildType() {
		return QMQualityIndicator.class;
	}

	@XmlElementWrapper(name="audience")
	@XmlElement(name="targetAudience")
	public List<Role> getTargetAudience() {
		return super.getTargetAudience();
	}
	
}
